#system
[battery]
full_symbol = '🔋 '
charging_symbol = '⚡️ '
discharging_symbol = '💀 '

[[battery.display]]
threshold = 20
style = 'bold red'

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[➜](bold red) '

[directory]
truncation_length = 3
truncation_symbol = '…/'

[package]
disabled = true

#languages
[nodejs]
format = '[🤖 $version](bold green) '
disabled = true

[golang]
format = '[$symbol($version )($mod_version )]($style)'
disabled = true

[terraform]
format = '[🌎 $version]($style) '

#applications
[aws]
format = 'on [$symbol($profile )($region )]($style)'
style = 'bold blue'
symbol = '☁️ '

[git_status]
conflicted = '🏳'
ahead = '🏎💨'
behind = '😰'
diverged = '😵'
up_to_date = '✓'
untracked = '🤷'
stashed = '📦'
modified = '📝'
staged = '[++\($count\)](green)'
renamed = '👅'
deleted = '🗑'

[kubernetes]
# format = '[k8s: $context](green) '
format = '[k8s](blue):[$context](blue)'
disabled = false
contexts = [
  { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "💔 " },
]
